# Generated by Django 2.0.4 on 2018-10-16 23:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0002_auto_20181009_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='回复内容')),
                ('reply_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='回复时间')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL, verbose_name='回复的目标用户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '回复表',
                'verbose_name_plural': '回复表',
            },
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.CharField(max_length=50, verbose_name='评论内容'),
        ),
    ]
