# Generated by Django 2.0.4 on 2018-10-16 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20181016_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='reply_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.Reply', verbose_name='回复'),
        ),
    ]
