# Generated by Django 2.0.4 on 2018-10-17 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_comments_reply_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='reply_list',
        ),
        migrations.AddField(
            model_name='reply',
            name='to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.Comments', verbose_name='回复的评论'),
        ),
    ]
